spring:
  profiles:
    default: dev

  r2dbc:
    url: r2dbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password

auth:
  jwt:
    issuer: jacob@cellok.kr

---

spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url:
    username:
    password:

auth:
  jwt:
    issuer: https://account-api-dev.wafflestudio.com

